# # Generate certificates for Elasticsearch. This has to be done only once and from the host machine.
# # The following commands are for Linux. For Windows, you can use Git Bash.
# # The commands are for Elasticsearch 8.17.2. If you are using a different version, please adjust the image tag accordingly.
# # In the Root Path of the project, create a folder named "elasticsearch-tls/config/certs" and put the "instances.yml" file on.
# # Run the following commands from the "elasticsearch-tls" folder of the project.
#
# sudo docker run --rm -it \
#  -v $(pwd)/config/certs:/usr/share/elasticsearch/config/certs \
#  --user "$(id -u):$(id -g)" \
#  docker.elastic.co/elasticsearch/elasticsearch:8.17.2 \
#  bin/elasticsearch-certutil ca --out config/certs/ca.p12 --pass
#
# openssl pkcs12 -in config/certs/ca.p12 -clcerts -nokeys -out config/certs/ca.crt
#
# sudo docker run --rm -it \
#  -v $(pwd)/config/certs:/usr/share/elasticsearch/config/certs \
#  --user "$(id -u):$(id -g)" \
#  docker.elastic.co/elasticsearch/elasticsearch:8.17.2 \
#  bin/elasticsearch-certutil cert --pem \
#  --ca config/certs/ca.p12 \
#  --in config/certs/instances.yml --out config/certs/bundle.zip
#
# unzip config/certs/bundle.zip -d config/certs/
# mv config/certs/es01/* config/certs/ && rm -rf config/certs/es01/ config/certs/bundle.zip && echo "Moved and deleted temp files. Everything is ready. Just run Docker Compose from the Root Project Path."

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=SuperSecurePassword123
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01.key
      - xpack.security.http.ssl.certificate=certs/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=certs/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca.crt
    volumes:
      - ./elasticsearch-tls/config/certs:/usr/share/elasticsearch/config/certs:ro
      - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
    restart: always

volumes:
  data:

networks:
  elastic:
    name: elastic
    driver: bridge
