filebeat.inputs:
  - type: tcp
    host: "0.0.0.0:5044"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  protocol: "https"
  username: "elastic"
  password: "SuperSecurePassword123"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.crt"]
  ssl.verification_mode: "full"

logging.level: info
