services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      N8N_HOST: "subdomain.singu.dev"
      N8N_PORT: 5678
      N8N_PROTOCOL: "https"
      NODE_ENV: "production"
      WEBHOOK_URL: "https://subdomain.singu.dev"
      GENERIC_TIMEZONE: "Europe/Madrid"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
      N8N_RUNNERS_MODE: "external"
      N8N_RUNNERS_AUTH_TOKEN: "supersecrettoken123"
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: "0.0.0.0"
      N8N_PROXY_HOPS: 1
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_DATABASE: "n8n"
      DB_POSTGRESDB_HOST: "db"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: "n8n"
      DB_POSTGRESDB_PASSWORD: "n8n"
      DB_POSTGRESDB_SCHEMA: "n8n"
    ports:
      - "5679:5679"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.n8n.rule=Host(`subdomain.singu.dev`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.middlewares=n8n@file
      - traefik.http.routers.n8n.tls.certResolver=letsencrypt
      - traefik.http.services.n8n-service.loadbalancer.server.scheme=http
      - traefik.http.services.n8n-service.loadbalancer.server.port=5678
    volumes:
      - node-data:/home/node/.n8n
      - local-files:/files
    networks:
      - traefik
      - n8n

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "n8n"
      POSTGRES_PASSWORD: "n8n"
      POSTGRES_DB: "n8n"
    ports:
      - "5432:5432"
    labels:
      - traefik.enable=false
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - n8n

volumes:
  data:
  node-data:
  local-files:

networks:
  traefik:
    name: traefik
    external: true

  n8n:
    name: n8n
    driver: bridge