services:
  runner-1:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-runner-1
    restart: always
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/task-runner-launcher javascript;"]
    environment:
      N8N_RUNNERS_AUTH_TOKEN: "supersecrettoken123"
      N8N_RUNNERS_MAX_CONCURRENCY: 5
      N8N_RUNNERS_TASK_BROKER_URI: "http://subdomain.singu.dev:5679"
      GENERIC_TIMEZONE: "Europe/Madrid"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5680/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - n8n-runners

networks:
  n8n-runners:
    name: n8n-runners
    driver: bridge