services:
  app:
    image: excalidraw/excalidraw:latest
    stdin_open: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.excalidraw.rule=Host(`draw.singu.dev`)
        - traefik.http.routers.excalidraw.entrypoints=websecure
        - traefik.http.routers.excalidraw.tls=true
        - traefik.http.services.excalidraw-service.loadbalancer.server.scheme=http
        - traefik.http.services.excalidraw-service.loadbalancer.server.port=80
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    networks:
      - traefik

volumes:
  notused:

networks:
  traefik:
    name: traefik
    external: true
