# In app.ini:
# [oauth2_client]
# REGISTER_EMAIL_CONFIRM   = false
# ENABLE_AUTO_REGISTRATION = true
# USERNAME                 = preferred_username
# ACCOUNT_LINKING          = auto

services:
  app:
    image: docker.gitea.com/gitea:1.23.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.gitea.rule=Host(`subdomain.singu.dev`)
        - traefik.http.routers.gitea.entrypoints=websecure
        - traefik.http.routers.gitea.tls=true
        - traefik.http.services.gitea-service.loadbalancer.server.scheme=http
        - traefik.http.services.gitea-service.loadbalancer.server.port=3000
    networks:
      - gitea
      - traefik
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  data:
  db:

networks:
  gitea:
    name: gitea
    driver: overlay
  traefik:
    name: traefik
    external: true
