# gitlab_rails['smtp_enable'] = true
# gitlab_rails['smtp_address'] = "smtp.singu.dev"
# gitlab_rails['smtp_port'] = 465
# gitlab_rails['smtp_user_name'] = "singu@singu.dev"
# gitlab_rails['smtp_password'] = ""
# gitlab_rails['smtp_domain'] = "singu.dev"
# gitlab_rails['smtp_authentication'] = "login"
# gitlab_rails['smtp_tls'] = true
# gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

services:
  app:
    image: gitlab/gitlab-ce:17.6.1-ce.0
    ports:
      - "2222:22"
      - "5432:5432"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - /home/singu/certs/cert.crt:/etc/gitlab/ssl/ssl.crt:ro
      - /home/singu/certs/cert.key:/etc/gitlab/ssl/ssl.key:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.gitlab.rule=Host(`subdomain.singu.dev`)
        - traefik.http.routers.gitlab.entrypoints=websecure
        - traefik.http.routers.gitlab.tls.certResolver=letsencrypt
        - traefik.http.services.gitlab-service.loadbalancer.server.scheme=https
        - traefik.http.services.gitlab-service.loadbalancer.server.port=443
    networks:
      - traefik

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://subdomain.singu.dev'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/ssl.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/ssl.key'

networks:
  traefik:
    name: traefik
    external: true
