services:
  app:
    image: grafana/grafana:11.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.grafana.rule=Host(`monitoring.singu.dev`)
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.tls=true
        - traefik.http.services.grafana-service.loadbalancer.server.scheme=http
        - traefik.http.services.grafana-service.loadbalancer.server.port=3000
    volumes:
      - data:/var/lib/grafana
    networks:
      - traefik

volumes:
  data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
