services:
  app:
    image: corentinth/it-tools:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.it-tools.rule=Host(`subdomain.singu.dev`)
        - traefik.http.routers.it-tools.entrypoints=websecure
        - traefik.http.routers.it-tools..certResolver=letsencrypt
        - traefik.http.services.it-tools-service.loadbalancer.server.scheme=http
        - traefik.http.services.it-tools-service.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
