services:
  it-tools:
    image: corentinth/it-tools:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.it-tools.rule=Host(`tools.singu.dev`)
        - traefik.http.routers.it-tools.entrypoints=websecure
        - traefik.http.routers.it-tools.tls=true
        - traefik.http.services.it-tools-service.loadbalancer.server.scheme=https
        - traefik.http.services.it-tools-service.loadbalancer.server.port=80
    restart: on-failure
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
