services:
  postgres:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak

  app:
    image: keycloak/keycloak:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.keycloak.rule=Host(`subdomain.singu.dev`)
        - traefik.http.routers.keycloak.entrypoints=websecure
        - traefik.http.routers.keycloak.tls=true
        - traefik.http.services.keycloak-service.loadbalancer.server.scheme=https
        - traefik.http.services.keycloak-service.loadbalancer.server.port=8443
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_HOSTNAME: keycloak.singu.dev
      KC_PROXY_HEADERS: forwarded
    volumes:
      - /home/singu/certs/cert.pem:/etc/x509/https/tls.crt
      - /home/singu/certs/cert.key:/etc/x509/https/tls.key
    depends_on:
      - postgres
    command:
      - start
    networks:
      - keycloak
      - traefik

networks:
  keycloak:
    name: keycloak
    driver: overlay
  traefik:
    name: traefik
    external: true

volumes:
  postgres:
    driver: local
