services:
  app:
    image: louislam/uptime-kuma:1
    volumes:
      - data:/app/data
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.kuma.rule=Host(`subdomain.singu.dev`)
        - traefik.http.routers.kuma.entrypoints=websecure
        - traefik.http.routers.kuma.tls.certResolver=letsencrypt
        - traefik.http.services.kuma-service.loadbalancer.server.scheme=http
        - traefik.http.services.kuma-service.loadbalancer.server.port=3001
    networks:
      - traefik

volumes:
  data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
