# keytool -importcert -file cert.pem  -keystore /opt/java/openjdk/lib/security/cacerts
# chown <user>:<user_group> -R /opt/buildagent

services:
  agent-1:
    image: jetbrains/teamcity-agent:2024.12.1-linux-sudo
    container_name: teamcity-docker-agent-1
    restart: always
    environment:
      SERVER_URL: "https://teamcity.singu.dev"
      AGENT_NAME: "AIPUS - Docker Agent 1"
      DOCKER_IN_DOCKER: start
    volumes:
      - "agent_1_config:/data/teamcity_agent/conf"
      - "docker_volumes:/var/lib/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/buildagent/system:/opt/buildagent/system"
      - "/opt/buildagent/plugins:/opt/buildagent/plugins"
      - "/opt/buildagent/tools:/opt/buildagent/tools"
      - "/opt/buildagent/temp:/opt/buildagent/temp"
      - "/opt/buildagent/work:/opt/buildagent/work"
#      - "/home/singu/certs:/certs:ro"
    privileged: true
    networks:
      - teamcity

volumes:
  agent_1_config:
    driver: local
  docker_volumes:
    driver: local

networks:
  teamcity:
    name: teamcity
