services:
  app:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: 1000
      PGID: 1000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.homepage.rule=Host(`home.singu.dev`)
        - traefik.http.routers.homepage.entrypoints=websecure
        - traefik.http.routers.homepage.tls=true
        - traefik.http.services.homepage-service.loadbalancer.server.scheme=http
        - traefik.http.services.homepage-service.loadbalancer.server.port=3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
