---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Home - Singu.DEV

background:
  image: https://raw.githubusercontent.com/singudotdev/singudotdev/refs/heads/master/assets/img/singudev-wallpaper-graffiti.png
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

layout:
  Hypervisor:
    header: true
    style: row
    columns: 1
  Portainer:
    header: true
    style: row
    columns: 3
  DNS:
    header: true
    style: row
    columns: 1
  Network:
    header: true
    style: row
    columns: 1
  UPS:
    header: true
    style: row
    columns: 1
  Development Places:
    header: true
    style: row
    columns: 2
