services:
  app:
    image: prom/node-exporter
    volumes:
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.exporter.rule=Host(`subdomain.singu.dev`) && PathPrefix(`/exporter/metrics`)
        - traefik.http.routers.exporter.entrypoints=websecure
        - traefik.http.routers.exporter.tls.certResolver=letsencrypt
        - traefik.http.routers.exporter.middlewares=strip-prefixes@file
        - traefik.http.services.exporter-service.loadbalancer.server.scheme=http
        - traefik.http.services.exporter-service.loadbalancer.server.port=9100
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
