services:
  app:
    image: bitnami/prometheus:3.0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik
        - traefik.http.routers.prometheus.rule=Host(`prometheus.singu.dev`)
        - traefik.http.routers.prometheus.entrypoints=websecure
        - traefik.http.routers.prometheus.tls=true
        - traefik.http.services.prometheus-service.loadbalancer.server.scheme=http
        - traefik.http.services.prometheus-service.loadbalancer.server.port=9090
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
