tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/cert.key

global:
  checkNewVersion: false
  sendAnonymousUsage: false

http:
  routers:
    router:
      rule: "Host(`subdomain.singu.dev`)"
      service: router-service
      tls: true
      entryPoints: websecure

  services:
    router-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.123:1337"
