# Static Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Enable debug logging
log:
  level: "DEBUG"
  filePath: ""  # Empty for stdout

# Access logs
accessLog: {}

# API and Dashboard
api:
  insecure: true
  dashboard: true

# Server transport configuration
serversTransport:
  insecureSkipVerify: true

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Let's Encrypt Certificate Resolver
certificatesResolvers:
  letsencrypt:
    acme:
      email: singu@singu.dev # DNS email
      storage: /letsencrypt/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Develop
      caServer: https://acme-v02.api.letsencrypt.org/directory # Production
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0s
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# Providers configuration
providers:
  docker: # or swarm
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "/traefik-config/config.yml"
    watch: true

# TLS configuration
tls:
  certificates:
    - certFile: "/certs/cert.pem"
      keyFile: "/certs/cert.key"

# Dynamic Configuration
http:
  routers:
    traefik-https:
      rule: "Host(`subdomain.singu.dev`)"
      service: "api@internal"
      tls:
        certResolver: letsencrypt
      entryPoints:
        - "websecure"
      middlewares:
        - "admin-auth"

    router:
      rule: "Host(`subdomain.singu.dev`)"
      service: "router-service"
      tls:
        certResolver: letsencrypt
      entryPoints:
        - "websecure"

  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "admin:$2y$05$stfJ9rdbKCrbweLKj3zeHOvS0MvOEXtmw3FBE8t5gk.aDrFY6h1A2"

    strip-prefixes:
      stripPrefix:
        prefixes:
          - "/endpoint/"

  services:
    router-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.123:1337" # or FQD (subdomain.tpz.es)