services:
  app:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/singu/certs:/certs:ro
      - /home/singu/docker/traefik/config.yml:/traefik-config/config.yml:ro
    command:
      - "--configFile=/traefik-config/config.yml"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    driver: overlay