# Create ./acme.json without content and set permissions in order to autogenerate certificates with letsencrypt
# touch ./acme.json
# chmod 600 ./acme.json

services:
  app:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/singu/certs:/certs:ro
      - /home/singu/docker/traefik/config.yml:/traefik-config/config.yml:ro
      - ./acme.json:/letsencrypt/acme.json
    environment:
      - CLOUDFLARE_DNS_API_TOKEN="API_TOKEN"
    command:
      - "--configFile=/traefik-config/config.yml"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    driver: overlay